add US1
jonashinzmann/MovieHUB pull request #7
Opened 2023-07-25 09:19 UTC by jonashinzmann

since I had problems with my original api, I am now using a different api. So far, this only delivers films for a specific search term. That will be superfluous when I have coded US2

2023-07-25 09:53 UTC, Roland-Hufnagel requested changes
Hi Jonas. That's a good starting point. But some important things are missing. Your US is not yet implemented. You have the components but they are not used anywhere. You have to adapt the ``pages/index.js``to make things happen. 
Also you can remove the things that you don't need anymore (what comes from the template like Heading and Subheading).
Further I left some comments. Have a look and try to improve your code.

2023-07-25 09:53 UTC, Roland-Hufnagel commented on components/Header/index.js
> +import React from "react";
Since this is a react-project you don't have to import React

2023-07-25 09:53 UTC, Roland-Hufnagel commented on components/Header/style.js
> +export const StyleHeader = styled.header`
Your US says the header should be fixed. I can't find that here!

2023-07-25 09:53 UTC, Roland-Hufnagel commented on components/MovieList/index.js
> +  const API_KEY = process.env.NEXT_PUBLIC_MOVIE_HUB_API_KEY;
I think this will not work. Please have a look at Frank's question in the Discussions-Board. It is complete the same thing.

2023-07-25 09:53 UTC, Roland-Hufnagel commented on components/MovieList/style.js
> +export const StyledDiv = styled.div`
I recommend:
export const StyledList = styled.ul`...`;

2023-07-26 11:54 UTC, MonaHer reviewed
LGTM :) 🚀

2023-07-26 12:31 UTC, merged